# 基本配置
name: "Legolas Blogs"
author: LegolasNg
url: https://legolasng.github.io/
resume_site: https://github.com/legolasNg/
baseurl: ""
description: keep it simple, stupid !
meta_description: 请叫我"小叶子"！
motto: Talk is cheap, Show me the code !
banner: legolas

# social
github:     https://github.com/legolasNg/
weibo:      http://weibo.com/wujianye
facebook:   
twitter:    
linkedin:   
email:      wujianye3@gmail.com

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: legolasNg

# markdown解析器
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

# 评论区设置
FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : legolas
    # disqus :
    #     short_name : legolasng
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
